import json
import os
from pathlib import Path

# Categories & Counts:
# Mains: 70
# Sides/Salads: 40
# Beverages: 20
# Desserts: 20
# Total: 150

mains = [
    # American & Sandwiches / Bowls (20)
    ("Grilled Chicken Pesto Sandwich", "Marinated grilled chicken breast, house pesto, provolone, and arugula on ciabatta.", ["lunch"], "mains", ["chicken breast", "pesto", "provolone cheese", "arugula", "ciabatta bread"], 8.50, ["dairy", "gluten", "tree nuts"], ["nut-free-option"], "1 sandwich"),
    ("Classic Turkey & Avocado Club", "Smoked turkey breast, avocado, crispy bacon, lettuce, and tomato on sourdough.", ["lunch"], "mains", ["turkey breast", "avocado", "bacon", "lettuce", "tomato", "mayonnaise", "sourdough bread"], 8.00, ["gluten", "eggs"], [], "1 sandwich"),
    ("Roast Beef & Horseradish Baguette", "Thinly sliced roast beef, horseradish aioli, caramelized onions, and watercress on a crisp baguette.", ["lunch"], "mains", ["roast beef", "horseradish aioli", "caramelized onions", "watercress", "baguette"], 9.00, ["gluten", "eggs"], [], "1 baguette"),
    ("Caprese Focaccia Panini", "Fresh mozzarella, ripe tomatoes, basil, and balsamic reduction pressed on focaccia.", ["lunch"], "mains", ["mozzarella", "tomatoes", "fresh basil", "balsamic glaze", "focaccia bread", "olive oil"], 7.50, ["dairy", "gluten"], ["vegetarian"], "1 panini"),
    ("Chipotle Steak Rice Bowl", "Grilled flank steak, cilantro lime rice, black beans, roasted corn salsa, and chipotle crema.", ["lunch", "dinner"], "mains", ["flank steak", "white rice", "cilantro", "lime", "black beans", "corn", "chipotle crema"], 10.50, ["dairy"], ["gluten-free"], "1 bowl (16 oz)"),
    ("BBQ Pulled Pork Slider Trio", "Slow-cooked pulled pork in sweet BBQ sauce served on brioche buns with coleslaw.", ["lunch"], "mains", ["pulled pork", "BBQ sauce", "brioche buns", "cabbage coleslaw"], 8.50, ["gluten", "eggs", "dairy"], [], "3 sliders"),
    ("Crispy Tofu & Quinoa Power Bowl", "Crispy baked tofu, quinoa, edamame, shredded carrots, and peanut sesame dressing.", ["lunch"], "mains", ["tofu", "quinoa", "edamame", "carrots", "peanut dressing", "sesame seeds"], 8.00, ["soy", "peanuts", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 bowl (16 oz)"),
    ("Buffalo Chicken Wrap", "Crispy buffalo chicken tenders, blue cheese crumble, shredded lettuce, and ranch in a spinach tortilla.", ["lunch"], "mains", ["chicken tenders", "buffalo sauce", "blue cheese", "lettuce", "ranch dressing", "spinach tortilla"], 8.00, ["dairy", "gluten", "eggs"], [], "1 wrap"),
    ("Black Bean & Sweet Potato Burrito", "Roasted sweet potato, black beans, brown rice, avocado, and salsa verde in a flour tortilla.", ["lunch"], "mains", ["sweet potato", "black beans", "brown rice", "avocado", "salsa verde", "flour tortilla"], 7.50, ["gluten"], ["vegan", "vegetarian", "dairy-free"], "1 burrito"),
    ("Grilled Salmon Teriyaki Plate", "Atlantic salmon fillet glazed with house teriyaki sauce, served with jasmine rice and steamed broccoli.", ["lunch", "dinner"], "mains", ["salmon", "teriyaki sauce", "jasmine rice", "broccoli", "sesame seeds"], 11.50, ["fish", "soy", "gluten", "sesame"], ["dairy-free"], "1 plate"),
    ("Mediterranean Chicken Gyro Box", "Herb-roasted chicken, tzatziki, cucumber tomato salad, and warm pita pockets.", ["lunch"], "mains", ["chicken thighs", "tzatziki sauce", "cucumbers", "tomatoes", "red onion", "pita bread"], 8.50, ["dairy", "gluten"], [], "1 meal box"),
    ("Smoked Ham & Swiss Croissant", "Honey smoked ham, aged Swiss cheese, and honey mustard on a flaky croissant.", ["lunch"], "mains", ["smoked ham", "swiss cheese", "honey mustard", "croissant"], 7.00, ["dairy", "gluten"], [], "1 croissant"),
    ("Cranberry Walnut Chicken Salad Wrap", "Diced chicken breast, dried cranberries, walnuts, and celery mayo wrap in wheat tortilla.", ["lunch"], "mains", ["chicken breast", "cranberries", "walnuts", "celery", "mayonnaise", "whole wheat tortilla"], 8.25, ["gluten", "tree nuts", "eggs"], [], "1 wrap"),
    ("Grilled Veggie & Hummus Wrap", "Roasted zucchini, bell peppers, eggplant, garlic hummus, and spinach in a wheat wrap.", ["lunch"], "mains", ["zucchini", "bell peppers", "eggplant", "hummus", "spinach", "whole wheat tortilla"], 7.25, ["gluten", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 wrap"),
    ("Steak Chimichurri Grain Bowl", "Char-broiled sirloin steak, farro, roasted tomatoes, pickled onions, and vibrant chimichurri.", ["lunch", "dinner"], "mains", ["sirloin steak", "farro", "roasted tomatoes", "pickled red onion", "parsley", "olive oil", "garlic"], 11.00, ["gluten"], ["dairy-free"], "1 bowl (16 oz)"),
    ("Lemon Herb Roasted Chicken Quarter", "Bone-in roasted chicken leg quarter seasoned with lemon, rosemary, and garlic.", ["lunch", "dinner"], "mains", ["chicken leg quarter", "lemon juice", "rosemary", "garlic", "olive oil"], 7.50, [], ["gluten-free", "dairy-free"], "1 chicken quarter"),
    ("Vegan Falafel Pita Box", "House-made crisp falafel balls, tahini drizzle, tabbouleh, and pita bread.", ["lunch"], "mains", ["chickpeas", "herbs", "tahini", "bulgur wheat", "parsley", "tomatoes", "pita bread"], 7.75, ["gluten", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 meal box"),
    ("Grilled Mahi Mahi Tacos", "Blackened mahi mahi, cabbage slaw, pico de gallo, and lime crema in corn tortillas.", ["lunch"], "mains", ["mahi mahi", "cabbage", "pico de gallo", "lime crema", "corn tortillas"], 10.00, ["fish", "dairy"], ["gluten-free"], "3 tacos"),
    ("Korean BBQ Beef Bulgogi Bowl", "Thinly sliced marinated beef, steamed rice, kimchi, pickled radishes, and toasted sesame seeds.", ["lunch", "dinner"], "mains", ["beef ribeye", "soy sauce", "sesame oil", "steamed rice", "kimchi", "pickled radish"], 10.50, ["soy", "sesame", "gluten"], ["dairy-free"], "1 bowl (16 oz)"),
    ("Plant-Based Meatball Sub", "Beyond Meat meatballs in marinara sauce topped with vegan mozzarella on a hoagie roll.", ["lunch"], "mains", ["plant-based meatballs", "marinara sauce", "vegan mozzarella", "hoagie roll"], 8.75, ["gluten", "soy"], ["vegan", "vegetarian", "dairy-free"], "1 sub"),

    # Italian & Pasta Mains (15)
    ("Chicken Parmesan over Penne", "Breaded chicken cutlet topped with marinara and melted mozzarella over penne pasta.", ["lunch", "dinner"], "mains", ["chicken cutlet", "breadcrumbs", "marinara", "mozzarella", "penne pasta"], 9.50, ["gluten", "dairy", "eggs"], [], "1 plate"),
    ("Classic Beef Lasagna Slice", "Layers of pasta, seasoned ground beef, ricotta, marinara, and melted mozzarella.", ["lunch", "dinner"], "mains", ["pasta sheets", "ground beef", "ricotta cheese", "marinara", "mozzarella"], 9.00, ["gluten", "dairy", "eggs"], [], "1 slice (12 oz)"),
    ("Vegetable Lasagna Rollups", "Spinach and ricotta rolled pasta baked in creamy garlic Alfredo and marinara.", ["lunch", "dinner"], "mains", ["pasta sheets", "spinach", "ricotta", "alfredo sauce", "marinara"], 8.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "2 rollups"),
    ("Penne Alla Vodka with Grilled Chicken", "Penne tossed in a rich tomato cream sauce infused with vodka, served with chicken breast.", ["lunch", "dinner"], "mains", ["penne pasta", "heavy cream", "tomato sauce", "vodka", "chicken breast", "parmesan"], 9.25, ["gluten", "dairy"], [], "1 portion (14 oz)"),
    ("Fettuccine Alfredo with Shrimp", "Sautéed jumbo shrimp served over egg fettuccine in a classic garlic parmesan cream sauce.", ["lunch", "dinner"], "mains", ["fettuccine pasta", "shrimp", "butter", "heavy cream", "parmesan", "garlic"], 11.50, ["gluten", "dairy", "shellfish", "eggs"], [], "1 portion (14 oz)"),
    ("Rigatoni Bolognese", "Slow-simmered beef and pork ragu tossed with al dente rigatoni pasta and fresh basil.", ["lunch", "dinner"], "mains", ["rigatoni", "ground beef", "ground pork", "tomatoes", "carrots", "celery", "parmesan"], 9.50, ["gluten", "dairy"], [], "1 portion (14 oz)"),
    ("Wild Mushroom Risotto", "Arborio rice cooked with wild forest mushrooms, white wine, thyme, and parmesan cheese.", ["lunch", "dinner"], "mains", ["arborio rice", "cremini mushrooms", "shiitake mushrooms", "white wine", "parmesan", "thyme"], 8.75, ["dairy"], ["vegetarian", "gluten-free"], "1 portion (14 oz)"),
    ("Spaghetti & Meatballs", "House beef meatballs served over spaghetti with traditional marinara sauce.", ["lunch", "dinner"], "mains", ["spaghetti", "beef meatballs", "marinara sauce", "parmesan cheese"], 8.75, ["gluten", "dairy", "eggs"], [], "1 portion (14 oz)"),
    ("Eggplant Parmesan", "Crispy pan-fried eggplant cutlets baked with marinara, fresh basil, and mozzarella.", ["lunch", "dinner"], "mains", ["eggplant", "breadcrumbs", "marinara sauce", "mozzarella", "parmesan"], 8.25, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 portion (12 oz)"),
    ("Tortellini in Creamy Pesto Sauce", "Cheese tortellini tossed with nut-free basil pesto cream sauce and cherry tomatoes.", ["lunch"], "mains", ["cheese tortellini", "heavy cream", "basil pesto", "cherry tomatoes", "parmesan"], 8.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 portion (12 oz)"),
    ("Chicken Piccata over Linguine", "Pan-seared chicken breast in a tangy lemon, butter, and caper sauce over linguine.", ["lunch", "dinner"], "mains", ["chicken breast", "lemon juice", "capers", "butter", "linguine pasta"], 9.75, ["gluten", "dairy"], [], "1 portion (14 oz)"),
    ("Baked Ziti Four Cheese", "Ziti pasta tossed with ricotta, mozzarella, parmesan, and provolone baked until bubbly.", ["lunch", "dinner"], "mains", ["ziti pasta", "ricotta", "mozzarella", "parmesan", "provolone", "marinara"], 8.00, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 portion (14 oz)"),
    ("Shrimp Scampi Pasta", "Garlic butter sautéed shrimp with white wine, lemon, and parsley over angel hair pasta.", ["lunch", "dinner"], "mains", ["shrimp", "garlic", "butter", "white wine", "lemon", "angel hair pasta"], 11.25, ["gluten", "dairy", "shellfish"], [], "1 portion (14 oz)"),
    ("Stuffed Shells Florentine", "Jumbo pasta shells stuffed with ricotta, spinach, and herbs baked in marinara.", ["lunch", "dinner"], "mains", ["jumbo pasta shells", "ricotta", "spinach", "mozzarella", "marinara"], 8.25, ["gluten", "dairy", "eggs"], ["vegetarian"], "3 shells"),
    ("Butternut Squash Ravioli", "Handmade ravioli filled with roasted butternut squash in a sage brown butter sauce.", ["lunch", "dinner"], "mains", ["ravioli pasta", "butternut squash", "butter", "sage", "parmesan"], 9.00, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 portion (12 oz)"),

    # Asian & Asian-Fusion Mains (15)
    ("Chicken Teriyaki Bento Box", "Teriyaki glazed chicken thigh served with jasmine rice, vegetable gyoza, and steamed edamame.", ["lunch"], "mains", ["chicken thigh", "teriyaki glaze", "jasmine rice", "vegetable gyoza", "edamame"], 9.50, ["soy", "gluten", "sesame"], ["dairy-free"], "1 bento box"),
    ("Pad Thai with Chicken & Shrimp", "Traditional stir-fried rice noodles with chicken, shrimp, egg, bean sprouts, peanuts, and lime.", ["lunch", "dinner"], "mains", ["rice noodles", "chicken breast", "shrimp", "eggs", "bean sprouts", "peanuts", "tamarind sauce"], 10.25, ["peanuts", "shellfish", "eggs", "fish"], ["gluten-free", "dairy-free"], "1 portion (16 oz)"),
    ("Beef & Broccoli Stir Fry", "Tender beef slices sauteed with fresh broccoli floret in a savory ginger soy glaze over rice.", ["lunch", "dinner"], "mains", ["flank steak", "broccoli", "soy sauce", "ginger", "garlic", "jasmine rice"], 9.75, ["soy", "gluten", "sesame"], ["dairy-free"], "1 portion (16 oz)"),
    ("Thai Red Curry Chicken", "Chicken breast simmered with bell peppers, bamboo shoots, and basil in coconut red curry sauce.", ["lunch", "dinner"], "mains", ["chicken breast", "coconut milk", "red curry paste", "bell peppers", "bamboo shoots", "jasmine rice"], 9.50, [], ["gluten-free", "dairy-free"], "1 portion (16 oz)"),
    ("Vegetable Fried Rice with Crispy Tofu", "Wok-fried jasmine rice with peas, carrots, green onions, egg, and crispy tofu.", ["lunch"], "mains", ["jasmine rice", "tofu", "eggs", "peas", "carrots", "soy sauce", "sesame oil"], 7.75, ["soy", "eggs", "sesame", "gluten"], ["vegetarian", "dairy-free"], "1 portion (14 oz)"),
    ("Sweet & Sour Chicken", "Crispy chicken bites tossed with pineapple, bell peppers, and onions in sweet & sour sauce.", ["lunch"], "mains", ["chicken breast", "pineapple", "bell peppers", "onions", "sweet & sour sauce", "white rice"], 8.75, ["gluten", "soy"], ["dairy-free"], "1 portion (14 oz)"),
    ("General Tso's Tofu", "Crispy tofu tossed in a spicy, sweet, and tangy General Tso sauce with broccoli.", ["lunch"], "mains", ["tofu", "soy sauce", "chili peppers", "broccoli", "white rice"], 8.00, ["soy", "gluten", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 portion (14 oz)"),
    ("Kung Pao Chicken", "Szechuan chicken stir-fried with peanuts, chili peppers, zucchini, and scallions.", ["lunch", "dinner"], "mains", ["chicken breast", "peanuts", "szechuan pepper", "zucchini", "soy sauce", "steamed rice"], 9.25, ["peanuts", "soy", "gluten", "sesame"], ["dairy-free"], "1 portion (14 oz)"),
    ("Miso Glazed Salmon", "Atlantic salmon baked with sweet miso glaze, served with bok choy and brown rice.", ["lunch", "dinner"], "mains", ["salmon", "white miso", "mirin", "bok choy", "brown rice"], 12.00, ["fish", "soy", "sesame"], ["gluten-free", "dairy-free"], "1 plate"),
    ("Panang Curry Tofu", "Rich and creamy Panang curry with tofu, green beans, and ground peanuts over jasmine rice.", ["lunch", "dinner"], "mains", ["tofu", "panang curry paste", "coconut milk", "green beans", "peanuts", "jasmine rice"], 8.50, ["peanuts"], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (16 oz)"),
    ("Chicken Lo Mein Noodles", "Egg noodles tossed with shredded chicken, cabbage, carrots, mushrooms, and savory lo mein sauce.", ["lunch"], "mains", ["egg noodles", "chicken breast", "cabbage", "carrots", "shiitake mushrooms", "soy sauce"], 8.50, ["gluten", "soy", "eggs", "sesame"], ["dairy-free"], "1 portion (14 oz)"),
    ("Orange Chicken Plate", "Crispy chicken tossed in tangy fresh orange glaze, served with fried rice.", ["lunch"], "mains", ["chicken breast", "orange glaze", "fried rice", "green onions"], 8.75, ["gluten", "soy", "eggs"], ["dairy-free"], "1 portion (14 oz)"),
    ("Singapore Street Noodles", "Thin vermicelli rice noodles stir-fried with curry powder, vegetables, and shrimp.", ["lunch", "dinner"], "mains", ["vermicelli noodles", "shrimp", "curry powder", "bell peppers", "bean sprouts", "scallions"], 10.00, ["shellfish", "soy", "eggs"], ["gluten-free", "dairy-free"], "1 portion (14 oz)"),
    ("Mongolian Beef", "Crispy sliced beef cooked with scallions and garlic in a sweet soy glaze over rice.", ["lunch", "dinner"], "mains", ["beef sirloin", "scallions", "garlic", "soy sauce", "brown sugar", "jasmine rice"], 10.25, ["soy", "gluten", "sesame"], ["dairy-free"], "1 portion (14 oz)"),
    ("Sesame Ginger Tofu & Noodle Bowl", "Chilled udon noodles with sesame ginger dressing, glazed tofu, cucumbers, and edamame.", ["lunch"], "mains", ["udon noodles", "tofu", "sesame ginger dressing", "cucumbers", "edamame"], 8.25, ["gluten", "soy", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 bowl (14 oz)"),

    # Mexican & Latin Mains (10)
    ("Carnitas Taco Platter", "Slow-braised pork carnitas served with warm corn tortillas, cilantro, onions, and salsa verde.", ["lunch", "dinner"], "mains", ["pork shoulder", "citrus marinade", "corn tortillas", "cilantro", "onion", "salsa verde"], 9.00, [], ["gluten-free", "dairy-free"], "3 tacos"),
    ("Chicken Enchiladas Suizas", "Shredded chicken wrapped in corn tortillas, covered with tomatillo cream sauce and melted Jack cheese.", ["lunch", "dinner"], "mains", ["chicken breast", "corn tortillas", "tomatillos", "sour cream", "jack cheese"], 8.75, ["dairy"], ["gluten-free"], "2 enchiladas"),
    ("Barbacoa Beef Burrito Bowl", "Slow-cooked shredded beef barbacoa, black beans, rice, pico de gallo, and guacamole.", ["lunch", "dinner"], "mains", ["beef chuck", "black beans", "cilantro rice", "pico de gallo", "guacamole"], 10.00, [], ["gluten-free", "dairy-free"], "1 bowl (16 oz)"),
    ("Cheese & Spinach Quesadilla", "Flour tortilla loaded with melted Monterey Jack, cheddar, sautéed spinach, and salsa.", ["lunch"], "mains", ["flour tortilla", "monterey jack cheese", "cheddar cheese", "spinach", "salsa"], 7.25, ["gluten", "dairy"], ["vegetarian"], "1 quesadilla"),
    ("Chile Relleno", "Poblano pepper stuffed with queso fresco, lightly battered and fried, topped with ranchero sauce.", ["lunch", "dinner"], "mains", ["poblano pepper", "queso fresco", "egg white batter", "ranchero tomato sauce"], 8.50, ["dairy", "eggs"], ["vegetarian", "gluten-free"], "1 pepper"),
    ("Fajita Chicken Bowl", "Seared chicken strips, sautéed bell peppers and onions, black beans, and yellow rice.", ["lunch"], "mains", ["chicken strips", "bell peppers", "onions", "black beans", "yellow rice", "salsa"], 9.00, [], ["gluten-free", "dairy-free"], "1 bowl (16 oz)"),
    ("Fish Tacos Baja Style", "Crispy beer-battered cod, chipotle cabbage slaw, and pico de gallo in soft flour tortillas.", ["lunch"], "mains", ["cod fillet", "beer batter", "flour tortillas", "cabbage", "chipotle aioli", "pico de gallo"], 9.50, ["fish", "gluten", "eggs"], [], "3 tacos"),
    ("Birria Beef Tacos with Consomé", "Braised beef birria, melted Oaxaca cheese, cilantro, and onion served with rich beef consomé.", ["lunch", "dinner"], "mains", ["beef chuck", "oaxaca cheese", "corn tortillas", "cilantro", "consomé dip"], 10.50, ["dairy"], ["gluten-free"], "3 tacos"),
    ("Vegan Sweet Potato Enchiladas", "Corn tortillas filled with sweet potato and black beans, baked in guajillo chili sauce.", ["lunch"], "mains", ["corn tortillas", "sweet potato", "black beans", "guajillo chili sauce", "cilantro"], 8.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "2 enchiladas"),
    ("Grilled Steak Quesadilla", "Marinated carne asada, melted cheese, roasted peppers, served with sour cream and guacamole.", ["lunch"], "mains", ["carne asada steak", "flour tortilla", "jack cheese", "sour cream", "guacamole"], 9.50, ["gluten", "dairy"], [], "1 quesadilla"),

    # Mediterranean & Middle Eastern Mains (10)
    ("Chicken Shawarma Plate", "Spiced roasted chicken slices served over turmeric rice with garlic toum sauce and pickled turnips.", ["lunch", "dinner"], "mains", ["chicken thighs", "shawarma spices", "turmeric rice", "garlic toum", "pickled turnips"], 9.25, [], ["gluten-free", "dairy-free"], "1 plate"),
    ("Beef & Lamb Gyro Platter", "Seasoned beef and lamb gyro meat, Greek salad, tzatziki, and warm pita bread.", ["lunch"], "mains", ["beef and lamb gyro meat", "cucumbers", "tomatoes", "feta cheese", "tzatziki", "pita bread"], 9.75, ["gluten", "dairy"], [], "1 platter"),
    ("Kofta Beef Kebab Bowl", "Grilled spiced beef kofta skewers served with saffron rice, grilled tomato, and tahini drizzle.", ["lunch", "dinner"], "mains", ["ground beef", "middle eastern spices", "saffron rice", "grilled tomato", "tahini"], 10.00, ["sesame"], ["gluten-free", "dairy-free"], "1 bowl (16 oz)"),
    ("Greek Chicken Souvlaki", "Marinated chicken skewers served with lemon roasted potatoes and Greek cucumber salad.", ["lunch", "dinner"], "mains", ["chicken breast", "oregano", "lemon", "roasted potatoes", "greek salad", "feta"], 9.50, ["dairy"], ["gluten-free"], "1 plate"),
    ("Veggie Mezze Platter Main", "Falafel, grape leaves, hummus, baba ghanoush, tabbouleh, olives, and pita bread.", ["lunch"], "mains", ["falafel", "grape leaves", "hummus", "baba ghanoush", "tabbouleh", "olives", "pita bread"], 8.75, ["gluten", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 platter"),
    ("Lamb Tagine with Couscous", "Slow-simmered lamb with apricots, almonds, and warm Moroccan spices over fluffy couscous.", ["lunch", "dinner"], "mains", ["lamb shoulder", "apricots", "almonds", "moroccan spices", "couscous"], 12.00, ["gluten", "tree nuts"], ["dairy-free"], "1 plate"),
    ("Chicken Kabob Skewers", "Grilled chicken, bell pepper, and onion skewers served with wild rice pilaf.", ["lunch", "dinner"], "mains", ["chicken breast", "bell peppers", "red onion", "wild rice pilaf"], 9.00, [], ["gluten-free", "dairy-free"], "2 skewers with rice"),
    ("Shakshuka with Pita", "Poached eggs in a spicy tomato, pepper, and onion sauce served with fresh pita bread.", ["lunch"], "mains", ["eggs", "tomatoes", "bell peppers", "onions", "cumin", "pita bread"], 7.75, ["eggs", "gluten"], ["vegetarian"], "1 bowl"),
    ("Spanakopita Meal", "Crispy phyllo pastry filled with spinach and feta cheese, served with Greek side salad.", ["lunch"], "mains", ["phyllo dough", "spinach", "feta cheese", "greek salad"], 8.25, ["gluten", "dairy", "eggs"], ["vegetarian"], "2 pieces with salad"),
    ("Grilled Salmon Mediterranean Bowl", "Herb salmon fillet, farro, cucumbers, cherry tomatoes, kalamata olives, and feta cheese.", ["lunch", "dinner"], "mains", ["salmon", "farro", "cucumbers", "tomatoes", "kalamata olives", "feta cheese"], 11.75, ["fish", "gluten", "dairy"], [], "1 bowl (16 oz)")
]

sides_salads = [
    # Salads (20)
    ("Classic Caesar Salad", "Romaine lettuce, house parmesan croutons, shaved parmesan, and creamy Caesar dressing.", ["lunch", "dinner"], "sides_salads", ["romaine lettuce", "croutons", "parmesan cheese", "caesar dressing"], 4.25, ["gluten", "dairy", "fish", "eggs"], ["vegetarian-option"], "1 side bowl"),
    ("Greek Farmer Salad", "Cucumbers, vine tomatoes, red onions, kalamata olives, and feta block with oregano vinaigrette.", ["lunch", "dinner"], "sides_salads", ["cucumbers", "tomatoes", "red onion", "kalamata olives", "feta cheese", "olive oil"], 4.50, ["dairy"], ["vegetarian", "gluten-free"], "1 side bowl"),
    ("Southwest Roasted Corn & Black Bean Salad", "Sweet corn, black beans, red bell pepper, cilantro, and lime vinaigrette.", ["lunch"], "sides_salads", ["sweet corn", "black beans", "bell pepper", "cilantro", "lime juice", "olive oil"], 4.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 side bowl"),
    ("Asian Sesame Crunchy Slaw", "Shredded napa cabbage, carrots, bell peppers, crispy wonton strips, and sesame ginger dressing.", ["lunch"], "sides_salads", ["napa cabbage", "carrots", "wonton strips", "sesame seeds", "ginger dressing"], 3.75, ["gluten", "soy", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 side bowl"),
    ("Garden House Salad", "Mixed greens, cherry tomatoes, cucumbers, shredded carrots, and choice of balsamic dressing.", ["lunch", "dinner"], "sides_salads", ["mixed greens", "cherry tomatoes", "cucumbers", "carrots", "balsamic vinaigrette"], 3.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 side bowl"),
    ("Caprese Skewers Salad", "Cherry tomatoes, fresh mozzarella pearls, basil leaves, and balsamic reduction.", ["lunch"], "sides_salads", ["cherry tomatoes", "mozzarella pearls", "fresh basil", "balsamic glaze"], 4.50, ["dairy"], ["vegetarian", "gluten-free"], "4 skewers"),
    ("Quinoa & Roasted Veggie Salad", "Tri-color quinoa, roasted zucchini, butternut squash, cranberries, and lemon dressing.", ["lunch"], "sides_salads", ["quinoa", "zucchini", "butternut squash", "dried cranberries", "lemon dressing"], 4.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 side bowl"),
    ("Cranberry Apple Walnut Salad", "Baby spinach, crisp green apples, dried cranberries, walnuts, and goat cheese crumble.", ["lunch", "dinner"], "sides_salads", ["baby spinach", "green apples", "cranberries", "walnuts", "goat cheese", "apple cider vinaigrette"], 4.75, ["dairy", "tree nuts"], ["vegetarian", "gluten-free"], "1 side bowl"),
    ("Mediterranean Couscous Salad", "Fluffy pearl couscous, sun-dried tomatoes, cucumbers, parsley, and lemon dressing.", ["lunch"], "sides_salads", ["pearl couscous", "sun-dried tomatoes", "cucumbers", "parsley", "lemon juice", "olive oil"], 4.00, ["gluten"], ["vegan", "vegetarian", "dairy-free"], "1 side bowl"),
    ("Kale & Pecan Power Salad", "Tuscan kale, toasted pecans, shaved parmesan, dried cherries, and lemon tahini dressing.", ["lunch"], "sides_salads", ["tuscan kale", "pecans", "parmesan cheese", "dried cherries", "tahini dressing"], 4.50, ["dairy", "tree nuts", "sesame"], ["vegetarian", "gluten-free"], "1 side bowl"),
    ("Cobb Side Salad", "Chopped romaine, hard-boiled egg, bacon bits, blue cheese, and tomato.", ["lunch"], "sides_salads", ["romaine lettuce", "hard-boiled egg", "bacon", "blue cheese", "tomatoes", "ranch dressing"], 4.75, ["dairy", "eggs"], ["gluten-free"], "1 side bowl"),
    ("Tabbouleh Salad", "Finely chopped parsley, mint, tomatoes, mint, bulgur wheat, and lemon olive oil dressing.", ["lunch"], "sides_salads", ["parsley", "mint", "tomatoes", "bulgur wheat", "lemon juice", "olive oil"], 3.75, ["gluten"], ["vegan", "vegetarian", "dairy-free"], "1 side bowl"),
    ("Strawberry Spinach Salad", "Baby spinach, fresh sliced strawberries, candied almonds, and poppyseed dressing.", ["lunch"], "sides_salads", ["spinach", "strawberries", "candied almonds", "poppyseed dressing"], 4.50, ["tree nuts"], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 side bowl"),
    ("Thai Cucumber Salad", "Thinly sliced cucumbers, red onions, cilantro, crushed peanuts, and sweet chili lime dressing.", ["lunch"], "sides_salads", ["cucumbers", "red onions", "cilantro", "peanuts", "sweet chili lime dressing"], 3.50, ["peanuts"], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 side bowl"),
    ("Pasta Salad Primavera", "Rotini pasta tossed with cherry tomatoes, black olives, bell peppers, mozzarella, and Italian dressing.", ["lunch"], "sides_salads", ["rotini pasta", "tomatoes", "olives", "bell peppers", "mozzarella pearls", "italian dressing"], 3.75, ["gluten", "dairy"], ["vegetarian"], "1 side bowl"),
    ("Orzo Spinach & Feta Salad", "Orzo pasta, baby spinach, crumbled feta, pine nuts, and lemon vinaigrette.", ["lunch"], "sides_salads", ["orzo pasta", "spinach", "feta cheese", "pine nuts", "lemon dressing"], 4.25, ["gluten", "dairy", "tree nuts"], ["vegetarian"], "1 side bowl"),
    ("Beet & Goat Cheese Salad", "Roasted red beets, arugula, goat cheese, pistachio nuts, and orange vinaigrette.", ["lunch"], "sides_salads", ["red beets", "arugula", "goat cheese", "pistachios", "orange vinaigrette"], 4.75, ["dairy", "tree nuts"], ["vegetarian", "gluten-free"], "1 side bowl"),
    ("Watermelon Feta Mint Salad", "Fresh cubed watermelon, crumbled feta, and fresh mint leaves with balsamic drizzle.", ["lunch"], "sides_salads", ["watermelon", "feta cheese", "fresh mint", "balsamic glaze"], 4.00, ["dairy"], ["vegetarian", "gluten-free"], "1 side bowl"),
    ("German Potato Salad", "Warm sliced potatoes tossed with crispy bacon, scallions, and tangy mustard vinegar dressing.", ["lunch"], "sides_salads", ["potatoes", "bacon", "scallions", "wholegrain mustard", "apple cider vinegar"], 4.00, [], ["gluten-free", "dairy-free"], "1 side bowl"),
    ("Creamy Broccoli Cheddar Salad", "Broccoli florets, sharp cheddar cheese, dried cranberries, sunflower seeds, and sweet mayo dressing.", ["lunch"], "sides_salads", ["broccoli", "cheddar cheese", "dried cranberries", "sunflower seeds", "mayonnaise"], 4.25, ["dairy", "eggs"], ["vegetarian", "gluten-free"], "1 side bowl"),

    # Hot Sides & Appetizers (20)
    ("Garlic Herb Roasted Potatoes", "Crispy oven-roasted baby potatoes seasoned with garlic, rosemary, and olive oil.", ["lunch", "dinner"], "sides_salads", ["baby potatoes", "garlic", "rosemary", "olive oil"], 3.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)"),
    ("Macaroni & Cheese Cup", "Elbow macaroni tossed in a creamy three-cheddar cheese sauce topped with breadcrumbs.", ["lunch"], "sides_salads", ["macaroni pasta", "cheddar cheese", "butter", "milk", "breadcrumbs"], 3.75, ["gluten", "dairy"], ["vegetarian"], "1 cup (8 oz)"),
    ("Steamed Garlic Broccoli", "Fresh broccoli florets steamed and tossed with minced garlic and extra virgin olive oil.", ["lunch", "dinner"], "sides_salads", ["broccoli", "garlic", "olive oil"], 3.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)"),
    ("Grilled Asparagus Spears", "Tender asparagus spears grilled with sea salt, lemon zest, and olive oil.", ["lunch", "dinner"], "sides_salads", ["asparagus", "lemon zest", "sea salt", "olive oil"], 3.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (5 oz)"),
    ("Roasted Sweet Potato Wedges", "Seasoned sweet potato wedges roasted until caramelized.", ["lunch", "dinner"], "sides_salads", ["sweet potatoes", "paprika", "olive oil", "sea salt"], 3.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)"),
    ("Vegetable Spring Rolls", "Crispy fried spring rolls filled with cabbage, carrots, and glass noodles, served with sweet chili sauce.", ["lunch"], "sides_salads", ["cabbage", "carrots", "glass noodles", "spring roll wrapper", "sweet chili sauce"], 3.50, ["gluten", "soy"], ["vegan", "vegetarian", "dairy-free"], "2 rolls"),
    ("Crispy Garlic Parmesan Breadsticks", "Freshly baked breadsticks brushed with garlic butter and sprinkled with parmesan.", ["lunch"], "sides_salads", ["flour dough", "garlic", "butter", "parmesan cheese"], 2.75, ["gluten", "dairy"], ["vegetarian"], "2 breadsticks"),
    ("Hummus & Warm Pita Chips", "House garlic hummus served with toasted seasoned pita chips.", ["lunch"], "sides_salads", ["chickpeas", "tahini", "garlic", "pita bread", "olive oil"], 3.50, ["gluten", "sesame"], ["vegan", "vegetarian", "dairy-free"], "1 portion"),
    ("Spanish Yellow Rice & Beans", "Seasoned yellow rice cooked with achiote, oregano, and tender black beans.", ["lunch", "dinner"], "sides_salads", ["long grain rice", "achiote seasoning", "black beans", "cilantro"], 2.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)"),
    ("Sauteed Green Beans Almondine", "Fresh green beans sautéed with butter, garlic, and toasted sliced almonds.", ["lunch", "dinner"], "sides_salads", ["green beans", "butter", "garlic", "sliced almonds"], 3.50, ["dairy", "tree nuts"], ["vegetarian", "gluten-free"], "1 portion (6 oz)"),
    ("Creamy Mashed Potatoes", "Butter and heavy cream whipped Yukon gold potatoes.", ["lunch", "dinner"], "sides_salads", ["yukon gold potatoes", "butter", "heavy cream", "chives"], 3.25, ["dairy"], ["vegetarian", "gluten-free"], "1 portion (6 oz)"),
    ("Cornbread Muffins", "Sweet golden cornmeal muffins served warm with honey butter.", ["lunch"], "sides_salads", ["cornmeal", "flour", "eggs", "milk", "butter", "honey"], 2.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "2 muffins"),
    ("Roasted Honey Glazed Carrots", "Baby carrots roasted with honey, thyme, and sea salt.", ["lunch", "dinner"], "sides_salads", ["baby carrots", "honey", "thyme", "olive oil"], 3.00, [], ["vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)"),
    ("Stuffed Mushrooms with Spinach & Herbs", "Button mushroom caps stuffed with seasoned spinach, garlic, and breadcrumbs.", ["lunch"], "sides_salads", ["mushrooms", "spinach", "breadcrumbs", "garlic", "parmesan"], 3.75, ["gluten", "dairy"], ["vegetarian"], "3 pieces"),
    ("BBQ Baked Beans", "Slow-cooked navy beans in smoked molasses BBQ sauce.", ["lunch"], "sides_salads", ["navy beans", "molasses", "bbq sauce", "onions", "mustard"], 2.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 cup (6 oz)"),
    ("Guacamole & Tortilla Chips", "Freshly smashed avocado, lime, cilantro, and red onion served with crispy corn chips.", ["lunch"], "sides_salads", ["avocados", "lime", "cilantro", "red onion", "corn tortilla chips"], 4.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion"),
    ("Fried Plantains (Tostones)", "Double-fried green plantains served with garlic mojo dipping sauce.", ["lunch"], "sides_salads", ["green plantains", "garlic", "olive oil", "lime juice"], 3.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "4 pieces"),
    ("Vegetable Samosas", "Crispy spiced potato and green pea pastries served with mint chutney.", ["lunch"], "sides_salads", ["potatoes", "peas", "pastry dough", "indian spices", "mint chutney"], 3.50, ["gluten"], ["vegan", "vegetarian", "dairy-free"], "2 samosas"),
    ("Loaded Potato Skins", "Crispy potato skins loaded with cheddar cheese, green onions, and sour cream.", ["lunch"], "sides_salads", ["potatoes", "cheddar cheese", "green onions", "sour cream"], 3.75, ["dairy"], ["vegetarian", "gluten-free"], "2 skins"),
    ("Charred Brussels Sprouts", "Charred brussels sprouts drizzled with balsamic glaze and toasted pine nuts.", ["lunch", "dinner"], "sides_salads", ["brussels sprouts", "balsamic glaze", "pine nuts", "olive oil"], 4.00, ["tree nuts"], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 portion (6 oz)")
]

beverages = [
    ("Fresh Cold-Pressed Lemonade", "House-made fresh squeezed lemonade with cane sugar.", ["lunch"], "beverages", ["water", "lemon juice", "cane sugar"], 2.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz bottle"),
    ("Iced Black Tea (Unsweetened)", "Freshly brewed premium black iced tea.", ["lunch"], "beverages", ["brewed black tea", "water"], 1.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz bottle"),
    ("Hibiscus Sweet Tea", "Brewed hibiscus tea sweetened with real sugar and mint.", ["lunch"], "beverages", ["water", "hibiscus flowers", "sugar", "mint"], 2.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz bottle"),
    ("Sparkling Citrus Water", "Zero-calorie sparkling water infused with natural lemon & lime.", ["lunch"], "beverages", ["carbonated water", "natural citrus flavor"], 1.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz can"),
    ("Cold Brew Coffee", "Smooth, low-acidity cold brewed artisanal coffee.", ["lunch"], "beverages", ["cold brewed coffee", "filtered water"], 2.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz bottle"),
    ("Fresh Orange Juice", "100% pure squeezed orange juice with pulp.", ["lunch"], "beverages", ["orange juice"], 2.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz bottle"),
    ("Cucumber Mint Detox Water", "Infused water with fresh cucumbers, mint leaves, and lime slices.", ["lunch"], "beverages", ["filtered water", "cucumber", "mint", "lime"], 1.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz cup"),
    ("Green Goddess Smoothie", "Spinach, green apple, banana, coconut water, and chia seeds.", ["lunch"], "beverages", ["spinach", "green apple", "banana", "coconut water", "chia seeds"], 3.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz cup"),
    ("Berry Blast Smoothie", "Strawberries, blueberries, raspberries, banana, and oat milk.", ["lunch"], "beverages", ["strawberries", "blueberries", "raspberries", "banana", "oat milk"], 3.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz cup"),
    ("Mango Lassi", "Traditional Indian yogurt drink blended with mango pulp and cardamom.", ["lunch"], "beverages", ["whole milk yogurt", "mango pulp", "sugar", "cardamom"], 3.25, ["dairy"], ["vegetarian", "gluten-free"], "12 oz cup"),
    ("Mexican Horchata", "Traditional rice milk drink spiced with cinnamon and vanilla.", ["lunch"], "beverages", ["rice milk", "cinnamon", "vanilla extract", "sugar"], 2.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz cup"),
    ("Matcha Green Tea Iced Latte", "Japanese matcha green tea whisked with oat milk and honey.", ["lunch"], "beverages", ["matcha powder", "oat milk", "honey", "water"], 3.50, [], ["vegetarian", "gluten-free", "dairy-free"], "12 oz cup"),
    ("Sparkling Apple Cider", "Non-alcoholic sparkling fresh apple cider.", ["lunch"], "beverages", ["apple juice", "carbonated water"], 2.25, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz bottle"),
    ("Ginger Beer (Non-Alcoholic)", "Spicy brewed ginger beer with natural cane sugar.", ["lunch"], "beverages", ["carbonated water", "ginger root", "cane sugar"], 2.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz bottle"),
    ("Coconut Water", "100% natural pure coconut water.", ["lunch"], "beverages", ["coconut water"], 2.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "11.1 oz carton"),
    ("Chai Iced Tea Latte", "Spiced black tea blend with cinnamon, cardamom, clove, and milk.", ["lunch"], "beverages", ["black tea", "spices", "whole milk", "cane sugar"], 3.25, ["dairy"], ["vegetarian", "gluten-free"], "12 oz cup"),
    ("Root Beer", "Craft non-alcoholic root beer made with real vanilla and cane sugar.", ["lunch"], "beverages", ["carbonated water", "cane sugar", "vanilla", "root beer extract"], 1.75, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "12 oz bottle"),
    ("Peach Iced Tea", "Sweet black iced tea infused with natural peach flavor.", ["lunch"], "beverages", ["black tea", "peach juice", "sugar"], 2.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz bottle"),
    ("Arnie Palmer", "Half fresh lemonade, half unsweetened black iced tea.", ["lunch"], "beverages", ["lemonade", "black iced tea"], 2.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16 oz cup"),
    ("Bottled Spring Water", "Pure natural spring water.", ["lunch"], "beverages", ["spring water"], 1.00, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "16.9 oz bottle")
]

desserts = [
    ("Fudgy Chocolate Brownie Bite", "Rich, dense chocolate brownie topped with chocolate drizzle.", ["lunch"], "desserts", ["chocolate", "butter", "flour", "sugar", "eggs", "cocoa powder"], 2.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 brownie square"),
    ("Classic Chocolate Chip Cookie", "Soft-baked butter cookie packed with semi-sweet chocolate chips.", ["lunch"], "desserts", ["flour", "butter", "chocolate chips", "brown sugar", "eggs"], 2.00, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 cookie (3 oz)"),
    ("New York Cheesecake Slice", "Rich creamy cheesecake on a graham cracker crust with strawberry coulis.", ["lunch", "dinner"], "desserts", ["cream cheese", "sugar", "eggs", "graham cracker crust", "strawberries"], 4.25, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 slice"),
    ("Mini Cannoli Trio", "Crispy pastry shells filled with sweet ricotta cream and mini chocolate chips.", ["lunch"], "desserts", ["ricotta cheese", "pastry shell", "powdered sugar", "chocolate chips"], 3.75, ["gluten", "dairy"], ["vegetarian"], "3 mini cannolis"),
    ("Key Lime Pie Tart", "Tangy key lime custard in a buttery graham crust topped with whipped cream.", ["lunch", "dinner"], "desserts", ["key lime juice", "condensed milk", "egg yolks", "graham crust", "whipped cream"], 3.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 mini tart"),
    ("Salted Caramel Blondie", "Brown sugar blondie swirled with salted caramel and white chocolate chips.", ["lunch"], "desserts", ["flour", "butter", "brown sugar", "caramel", "white chocolate"], 2.75, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 blondie square"),
    ("Tiramisu Cup", "Espresso-soaked ladyfingers layered with mascarpone cream and dusted with cocoa.", ["lunch", "dinner"], "desserts", ["ladyfingers", "espresso", "mascarpone cheese", "heavy cream", "cocoa powder"], 4.00, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 cup"),
    ("Assorted Macaron Trio", "French almond meringue cookies with vanilla, raspberry, and pistachio fillings.", ["lunch"], "desserts", ["almond flour", "egg whites", "sugar", "butter", "pistachios", "raspberries"], 4.50, ["tree nuts", "eggs", "dairy"], ["vegetarian", "gluten-free"], "3 macarons"),
    ("Vegan Chocolate Avocado Mousse", "Silky dark chocolate mousse made with ripe avocados and maple syrup.", ["lunch"], "desserts", ["avocado", "cocoa powder", "maple syrup", "vanilla extract", "almond milk"], 3.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 cup (4 oz)"),
    ("Lemon Bars", "Sweet tangy lemon curd on a shortbread crust dusted with powdered sugar.", ["lunch"], "desserts", ["flour", "butter", "sugar", "lemons", "eggs"], 2.50, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 bar"),
    ("Berry Parfait", "Greek yogurt layered with mixed berries, honey, and house granola.", ["lunch"], "desserts", ["greek yogurt", "blueberries", "strawberries", "honey", "rolled oats", "almonds"], 3.25, ["dairy", "tree nuts", "gluten"], ["vegetarian"], "1 cup (6 oz)"),
    ("Churro Bites with Dulce de Leche", "Crispy cinnamon sugar fried dough bites served with warm caramel sauce.", ["lunch"], "desserts", ["flour", "butter", "cinnamon", "sugar", "dulce de leche"], 3.25, ["gluten", "dairy"], ["vegetarian"], "5 bites"),
    ("Apple Crumble Tart", "Spiced cinnamon apples baked in a pastry shell with rolled oat crumble.", ["lunch", "dinner"], "desserts", ["apples", "flour", "rolled oats", "cinnamon", "butter", "brown sugar"], 3.50, ["gluten", "dairy"], ["vegetarian"], "1 mini tart"),
    ("Red Velvet Cupcake", "Moist red velvet cake topped with cream cheese frosting.", ["lunch"], "desserts", ["flour", "cocoa powder", "butter", "cream cheese", "sugar", "eggs"], 2.75, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 cupcake"),
    ("Peanut Butter Fudge Brownie", "Fudgy brownie with a peanut butter swirl and roasted peanut bits.", ["lunch"], "desserts", ["flour", "peanut butter", "cocoa powder", "butter", "peanuts", "eggs"], 2.75, ["gluten", "dairy", "peanuts", "eggs"], ["vegetarian"], "1 brownie square"),
    ("Coconut Mango Rice Pudding", "Sweet coconut sticky rice served with fresh mango slices and toasted sesame.", ["lunch"], "desserts", ["sticky rice", "coconut milk", "sugar", "mango", "sesame seeds"], 3.25, ["sesame"], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "1 cup (6 oz)"),
    ("Double Chocolate Chip Muffin", "Rich chocolate muffin studded with chocolate chunks.", ["lunch"], "desserts", ["flour", "cocoa powder", "chocolate chunks", "milk", "eggs", "butter"], 2.25, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 muffin"),
    ("Gluten-Free Flourless Chocolate Cake", "Decadent dense dark chocolate cake served with fresh raspberry.", ["lunch", "dinner"], "desserts", ["dark chocolate", "butter", "eggs", "sugar", "raspberries"], 4.00, ["dairy", "eggs"], ["vegetarian", "gluten-free"], "1 slice"),
    ("Oatmeal Raisin Cookie", "Chewy whole grain oat cookie packed with raisins and cinnamon.", ["lunch"], "desserts", ["rolled oats", "flour", "raisins", "butter", "brown sugar", "cinnamon", "eggs"], 2.00, ["gluten", "dairy", "eggs"], ["vegetarian"], "1 cookie (3 oz)"),
    ("Fresh Fruit Skewer", "Pineapple, melon, grapes, and strawberries on a bamboo skewer.", ["lunch"], "desserts", ["pineapple", "cantaloupe", "honeydew", "grapes", "strawberries"], 2.50, [], ["vegan", "vegetarian", "gluten-free", "dairy-free"], "2 skewers")
]

items = []
item_counter = 1

for item_list in [mains, sides_salads, beverages, desserts]:
    for name, desc, meals, cat, ingr, price, allergens, dietary, serving in item_list:
        items.append({
            "id": item_counter,
            "name": name,
            "description": desc,
            "meal_types": meals,
            "category": cat,
            "ingredients": ingr,
            "price": price,
            "allergens": allergens,
            "dietary_labels": dietary,
            "serving_size": serving
        })
        item_counter += 1

script_dir = Path(__file__).resolve().parent
output_path = script_dir.parent.parent / "data" / "catering_menu.json"
output_path.parent.mkdir(parents=True, exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    for item in items:
        f.write(json.dumps(item) + "\n")

print(f"Successfully generated {len(items)} items in {output_path} (Newline-Delimited JSON format for BigQuery)")

